In [22]:
import numpy as np
from math import log

In [2]:
def parse_libsvm_file(filename):
    labels = []
    features = []

    with open(filename, 'r') as file:
        for line in file:
            elements = line.strip().split(' ')
            labels.append(int(elements[0]))
            feature_vector = {}
            for item in elements[1:]:
                index, value = item.split(':')
                feature_vector[int(index)] = float(value)
            features.append(feature_vector)

    return labels, features

In [6]:
labels, features = parse_libsvm_file("./a7a.train")

In [7]:
labels

[-1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,


In [8]:
features

[{3: 1.0,
  11: 1.0,
  14: 1.0,
  19: 1.0,
  39: 1.0,
  42: 1.0,
  55: 1.0,
  64: 1.0,
  67: 1.0,
  73: 1.0,
  75: 1.0,
  76: 1.0,
  80: 1.0,
  83: 1.0},
 {3: 1.0,
  6: 1.0,
  17: 1.0,
  22: 1.0,
  36: 1.0,
  41: 1.0,
  53: 1.0,
  64: 1.0,
  67: 1.0,
  73: 1.0,
  74: 1.0,
  76: 1.0,
  80: 1.0,
  83: 1.0},
 {3: 1.0,
  6: 1.0,
  18: 1.0,
  29: 1.0,
  39: 1.0,
  40: 1.0,
  51: 1.0,
  61: 1.0,
  67: 1.0,
  72: 1.0,
  74: 1.0,
  76: 1.0,
  80: 1.0,
  83: 1.0},
 {4: 1.0,
  6: 1.0,
  16: 1.0,
  26: 1.0,
  35: 1.0,
  45: 1.0,
  49: 1.0,
  64: 1.0,
  71: 1.0,
  72: 1.0,
  74: 1.0,
  76: 1.0,
  78: 1.0,
  101: 1.0},
 {3: 1.0,
  6: 1.0,
  18: 1.0,
  20: 1.0,
  37: 1.0,
  40: 1.0,
  51: 1.0,
  63: 1.0,
  71: 1.0,
  73: 1.0,
  74: 1.0,
  76: 1.0,
  82: 1.0,
  83: 1.0},
 {3: 1.0,
  6: 1.0,
  15: 1.0,
  25: 1.0,
  38: 1.0,
  40: 1.0,
  48: 1.0,
  63: 1.0,
  68: 1.0,
  73: 1.0,
  74: 1.0,
  76: 1.0,
  80: 1.0},
 {3: 1.0,
  6: 1.0,
  17: 1.0,
  27: 1.0,
  35: 1.0,
  40: 1.0,
  57: 1.0,
  63: 1.0,
  69:

In [10]:
num_samples = len(features)
num_features = max(max(sample.keys()) for sample in features)
X = np.zeros((num_samples, num_features))

In [13]:
print("No of samples:", num_samples)
print("No of fetaures:", num_features)

No of samples: 16100
No of fetaures: 122


In [15]:
# array of values
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [17]:
#inserting values of features into the Array
for i, sample in enumerate(features):
        for j, value in sample.items():
            X[i, j - 1] = value  # Adjust index to start from 0

    # Convert labels to a numpy array
y = np.array(labels)


In [82]:
X

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [83]:
y


array([-1, -1, -1, ...,  1, -1,  1])

In [99]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def initialize_params(num_features):
    # Initialize weights with zeros 
    w = np.zeros(num_features)
    w0 = 0
    return w0, w

def logistic_reg(X, y, learning_rate, N):
    num_samples, num_features = X.shape
    b, w = initialize_params(num_features)

    for i in range(N):
        # compute predicted
        dot_prod = np.dot(X, w)
        z =  dot_prod + b
        A = sigmoid(y*z)

        # Compute loss
        loss = np.sum(-1*np.log(A))
        
        # Backward pass: compute gradients
        dw = (1-A)*y*X.T
        db = np.mean(A)

        # Update parameters
        w -= learning_rate * dw
        b -= learning_rate * db

        # Print the loss every 100 iterations
        if i%100==0:
            print (f"Iterations {i}: Loss {loss}")

    return w, b

